---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: 请参见适用于您的Trident配置的配置选项。 
---
= 存储配置选项
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请参见适用于您的Trident配置的配置选项。



== 全局配置选项

无论使用哪个存储平台、这些配置选项都适用于所有Trident配置。

[cols="3*"]
|===
| 选项 | Description | 示例 


| `ve版本`  a| 
配置文件版本号
 a| 
`1`



| `storageDriverName`  a| 
存储驱动程序的名称
 a| 
`ontap-nas`， `ontap-san`， `ontap-nas-economy`，
`ontap-nas-flexgroup`， `solidfire-san`



| `s存储前缀`  a| 
卷名称的可选前缀。默认值： `netappdvp_`。
 a| 
`staging_`



| `limitVolumeSize`  a| 
卷大小的可选限制。默认值：""(未强制实施)
 a| 
`10g`

|===

TIP: 不要对元素后端使用 `storagePrefix`(包括默认值)。默认情况下， `solidfire-san`驱动程序将忽略此设置，而不使用前缀。NetApp建议对Docker卷映射使用特定的租户ID、或者在可能已使用任何名称创建的情况下使用由Docker版本、驱动程序信息和原始名称填充的属性数据。

您可以使用默认选项来避免在创建的每个卷上指定这些选项。`s` 选项适用于所有控制器类型。有关如何设置默认卷大小的示例，请参见 ONTAP 配置一节。

[cols="3*"]
|===
| 选项 | Description | 示例 


| `s大小`  a| 
新卷的可选默认大小。默认值： `1G`
 a| 
`10G`

|===


== ONTAP 配置

除了上述全局配置值之外，在使用 ONTAP 时，还可以使用以下顶级选项。

[cols="3*"]
|===
| 选项 | Description | 示例 


| `m年` 月 日  a| 
ONTAP 管理 LIF 的 IP 地址。您可以指定完全限定域名（ FQDN ）。
 a| 
`10.0.0.1`



| `dataLIF`  a| 
协议 LIF 的 IP 地址。

* ONTAP NAS驱动程序*：NetApp建议指定 `dataLIF`。如果未提供此参数、则Trident将从SVM提取数据LIF。您可以指定要用于NFS挂载操作的完全限定域名(FQDN)、以便创建轮叫DNS来在多个dataLIF之间进行负载平衡。

*SAN ONTAP驱动程序*:不指定用于iSCSI或FC。Trident使用link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP 选择性LUN映射"^]发现建立多路径会话所需的iSCSI或FC LUN。如果明确定义、则会生成警告 `dataLIF`。
 a| 
`10.0.0.2`



| `sVM`  a| 
要使用的 Storage Virtual Machine （如果管理 LIF 为集群 LIF ，则为必填项）
 a| 
`svm_nfs`



| `用户名`  a| 
用于连接到存储设备的用户名
 a| 
`vsadmin`



| `密码`  a| 
用于连接到存储设备的密码
 a| 
`secret`



| `聚合`  a| 
要配置的聚合（可选；如果设置了聚合，则必须将其分配给 SVM ）。对于 `ontap-nas-flexgroup`驱动程序、此选项将被忽略。分配给SVM的所有聚合均用于配置FlexGroup卷。
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
可选，如果使用量超过此百分比，则配置失败
 a| 
`75%`



| `nfsMountOptions`  a| 
对NFS挂载选项进行精细控制；默认为"-o nfsvers=3"。*仅适用于 `ontap-nas`和 `ontap-nas-economy`驱动程序*。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["请参见此处的 NFS 主机配置信息"^](英文)。
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident会将每个节点创建和管理 `igroups`为 `netappdvp`。

此值不能更改或省略。

*仅适用于 `ontap-san` 驱动程序*。
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
可要求的最大卷大小。
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
每个 FlexVol 的最大 qtree 数必须在 50 ， 300 范围内，默认值为 200 。

*用于 `ontap-nas-economy` 驱动程序、此选项允许自定义每个qtree*的最大FlexVol 数。
 a| 
`300`



 a| 
`sanType`
| *仅支持 `ontap-san`驱动程序。*用于为iSCSI、 `nvme`NVMe/TCP或基于光纤通道的 `fcp`SCSI (FC)选择 `iscsi`。 | `iscsi` 如果为空 


| `limitVolumePoolSize` | * `ontap-san-economy` `ontap-san-economy`仅支持和驱动程序。*限制ONTAP ONTAP经济型和ONTAP经济型驱动程序中的FlexVol大小。  a| 
`300g`

|===
您可以使用默认选项来避免在创建的每个卷上指定这些选项：

[cols="1,3,2"]
|===
| 选项 | Description | 示例 


| `s页面预留`  a| 
空间预留模式； `none` (精简配置)或 `volume` (厚)
 a| 
`无`



| `sSnapshot 策略`  a| 
要使用的Snapshot策略、默认为 `none`
 a| 
`无`



| `sSnapshot 预留`  a| 
Snapshot预留百分比、默认值为""以接受ONTAP默认值
 a| 
`10`



| `splitOnClone`  a| 
创建克隆时将其从父级拆分、默认为 `false`
 a| 
`false`



| `加密`  a| 
在新卷上启用NetApp卷加密(NVE)；默认为`false`。要使用此选项，必须在集群上获得 NVE 的许可并启用 NVE 。

如果在后端启用了NAE、则在Trident中配置的任何卷都将启用NAE。

有关详细信息，请参阅：link:../trident-reco/security-reco.html["Trident如何与NVE和NAE配合使用"]。
 a| 
true



| `unixPermissions`  a| 
对于已配置的NFS卷、NAS选项默认为 `777`
 a| 
`777`



| `snapshotDir`  a| 
用于访问目录的NAS选项 `.snapshot`。
 a| 
对于NFSv4、为"TRUE"；对于NFSv3、为"false"



| `exportPolicy`  a| 
要使用的NFS导出策略的NAS选项、默认为 `default`
 a| 
`default`



| `securityStyle`  a| 
用于访问已配置NFS卷的NAS选项。

NFS支持 `mixed` 和 `unix` 安全模式。默认值为 `unix`。
 a| 
`unix`



| `fileSystemType`  a| 
SAN选项要选择文件系统类型、默认为 `ext4`
 a| 
`xfs`



| `分层策略`  a| 
要使用的分层策略，默认为 `none`。
 a| 
`无`

|===


=== 扩展选项

 `ontap-nas`和 `ontap-san`驱动程序会为每个Docker卷创建一个ONTAP FlexVol。ONTAP支持每个集群节点多达1000个FlexVol、集群最多12、000个FlexVol卷如果您的Docker卷要求符合此限制、则该驱动程序是首选NAS解决方案、因为它 `ontap-nas`具有FlexVol提供的其他功能、例如Docker卷粒度快照和克隆。

如果所需的 Docker 卷数超出 FlexVol 限制所能容纳的范围，请选择 `ontap-nas-economy"` 或 `ontap-san-economy"` 驱动程序。

此 `ontap-nas-economy`驱动程序会在自动管理的FlexVol卷池中将Docker卷创建为ONTAP qtrees。qtree 的扩展能力远高于此，每个集群节点最多可扩展 100 ， 000 个，每个集群最多可扩展 2 ， 400 ， 000 个，但某些功能会受到影响。该 `ontap-nas-economy`驱动程序不支持Docker卷粒度快照或克隆。


NOTE: Docker Swarm目前不支持此 `ontap-nas-economy`驱动程序、因为Docker Swarm不会在多个节点之间编排卷创建过程。

此 `ontap-san-economy`驱动程序会在自动管理的FlexVol卷共享池中将Docker卷创建为ONTAP LUN。这样，每个 FlexVol 就不会仅限于一个 LUN ，并且可以为 SAN 工作负载提供更好的可扩展性。根据存储阵列的不同， ONTAP 每个集群最多支持 16384 个 LUN 。由于卷是下面的 LUN ，因此此驱动程序支持 Docker 卷粒度快照和克隆。

选择 `ontap-nas-flexgroup`一个驱动程序来提高单个卷的并行处理能力、该卷可能会增长到包含数十亿个文件的PB级范围。FlexGroup 的一些理想用例包括 AI/ML/DL ，大数据和分析，软件构建，流式传输，文件存储库等。配置FlexGroup卷时、Trident会使用分配给SVM的所有聚合。Trident 中的 FlexGroup 支持还需要注意以下事项：

* 需要 ONTAP 9.2 或更高版本。
* 截至本文撰写时， FlexGroup 仅支持 NFS v3 。
* 建议为 SVM 启用 64 位 NFSv3 标识符。
* 建议的最小FlexGroup成员/卷大小为 100 GiB。
* FlexGroup卷不支持克隆。


有关适用于FlexGroup的FlexGroup和工作负载的信息，请参见 https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["《NetApp FlexGroup卷最佳实践和实施指南》"^]。

要在同一环境中获得高级功能和大规模扩展，您可以运行多个Docker卷插件实例，其中一个使用，另一个 `ontap-nas-economy`使用 `ontap-nas`。



=== Trident的自定义ONTAP角色

您可以创建Privileges最低的ONTAP集群角色、这样就不必使用ONTAP管理员角色在Trident中执行操作。如果在Trident后端配置中包含用户名、则Trident将使用您创建的ONTAP集群角色来执行操作。

有关创建Trident自定义角色的详细信息、请参见link:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Trident自定义角色生成器"]。

[role="tabbed-block"]
====
.使用ONTAP命令行界面
--
. 使用以下命令创建新角色：
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. 为Trident用户创建用户名：
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. 将角色映射到用户：
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.使用 System Manager
--
在ONTAP系统管理器中执行以下步骤：

. *创建自定义角色*：
+
.. 要在集群级别创建自定义角色，请选择*Cluster > Settings*。
+
(或)要在SVM级别创建自定义角色、请选择*存储> Storage VM `required SVM` >>设置>用户和角色*。

.. 选择*用户和角色*旁边的箭头图标(*->*)。
.. 在*角色*下选择*+添加*。
.. 定义角色的规则，然后单击*Save*。


. *将角色映射到Trident user*：+在*Users and Roles*页面上执行以下步骤：
+
.. 在*用户*下选择添加图标*+*。
.. 选择所需的用户名，然后在下拉菜单中为*rouser*选择一个角色。
.. 单击 * 保存 * 。




--
====
有关详细信息、请参见以下页面：

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["用于管理ONTAP的自定义角色"^]或link:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["定义自定义角色"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["使用角色和用户"^]




=== ONTAP 配置文件示例

.<code>ontap-nas</code> 驱动程序的NFS示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.<code>ontap-nas-flexgroup</code> 驱动程序的NFS示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.<code>ontap-nas-economy</code> 驱动程序的NFS示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.<code>ontap-san</code> 驱动程序的iSCSI示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.<code>ontap-san-economy</code> 驱动程序的NFS示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.NVMe/TCP <code>ontap-san</code> 驱动程序示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.<code> ONTAP－</code>驱动程序的基于FC的SCSI示例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Element 软件配置

除了全局配置值之外，在使用 Element 软件（ NetApp HCI/SolidFire ）时，还可以使用这些选项。

[cols="3*"]
|===
| 选项 | Description | 示例 


| `端点`  a| 
https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
https://admin:admin@192.168.160.3/json-rpc/8.0



| `sVIP`  a| 
iSCSI IP 地址和端口
 a| 
10.0.0.7 ： 3260



| `租户名称`  a| 
要使用的 SolidFireF 租户（如果未找到，则创建）
 a| 
`docker`



| `InitiatorIFace`  a| 
将 iSCSI 流量限制为非默认接口时，请指定接口
 a| 
`default`



| `类型`  a| 
QoS 规范
 a| 
请参见以下示例



| `LegendPrefix`  a| 
升级后的 Trident 安装的前缀。如果您使用的是1.3.2之前的版本的Trident并对现有卷执行升级、则需要设置此值才能访问通过volume-name方法映射的旧卷。
 a| 
`netappdvp-`

|===
`solidfire-san` 驱动程序不支持 Docker Swarm 。



=== Element 软件配置文件示例

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----