---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, Trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: 您应使用与安装Trident相同的方法卸载Trident。如果您需要修复在升级、依赖关系问题或升级失败或不完整后发现的错误、则应卸载Trident、然后按照该版本的特定说明重新安装早期版本。 
---
= 卸载 Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应使用与安装Trident相同的方法卸载Trident。

.关于此任务
* 如果您需要修复在升级、依赖关系问题或升级失败或不完整后发现的错误，则应卸载Trident，然后按照适用于该版本的特定说明重新安装早期版本link:../earlier-versions.html["version"]。这是将_降 级_降级到早期版本的唯一建议方法。
* 为了便于升级和重新安装、卸载Trident不会删除Trident创建的CRD或相关对象。如果需要完全删除Trident及其所有数据，请参见link:../troubleshooting.html#completely-remove-trident-and-crds["完全删除Trident和CRD"]。


.开始之前
如果要停用Kubnetes集群、则必须在卸载之前删除使用Trident创建的卷的所有应用程序。这样可以确保在删除之前、在Kubbernetes节点上未取消对这些PVC的审核。



== 确定原始安装方法

您应使用与安装Trident相同的方法来卸载它。卸载之前、请验证最初安装Trident时使用的版本。

. 使用 ... `kubectl get pods -n trident` 检查Pod。
+
** 如果没有操作员POD，则使用安装了Trident `tridentctl`。
** 如果有操作员POD、则Trident是使用Trident操作员手动或使用Helm安装的。


. 如果有操作员POD、请使用 `kubectl describe tproc trident`确定Trident是否是使用Helm安装的。
+
** 如果有Helm标签、则Trident是使用Helm安装的。
** 如果没有Helm标签、则Trident是使用Trident操作员手动安装的。






== 卸载TRIdent操作员安装

您可以手动卸载或使用Helm卸载TRYDent操作员安装。



=== 卸载手动安装

如果您使用操作员安装了Trident、则可以通过执行以下操作之一将其卸载：

. *编辑 `TridentOrchestrator` CR并设置卸载标志**：
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
当 `uninstall` 标志设置为 `true`、Trident操作符将卸载Trident、但不会删除Trident Orchestrator本身。如果要重新安装 Trident ，应清理 Trident Orchestrator 并创建新的 Trident 。

. **删除 `TridentOrchestrator`**:删除用于部署Trident的CR后 `TridentOrchestrator`，您将指示操作员卸载Trident。操作员将处理Trident部署和守护进程的删除过程、并继续删除此部署和守护进程 `TridentOrchestrator`、同时删除其在安装过程中创建的Trident Pod。
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== 卸载Helm安装

如果您使用Helm安装了Trident，则可以使用将其卸载 `helm uninstall`。

[listing]
----
#List the Helm release corresponding to the Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== 卸载 `tridentctl` 安装

使用 `uninstall`中的命令 `tridentctl`删除与Trident关联的所有资源(CRD和相关对象除外)：

[listing]
----
./tridentctl uninstall -n <namespace>
----