---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: '了解如何使用 `kubectl` 执行后端管理操作。' 
---
= 使用 kubectl 执行后端管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解如何使用 `kubectl` 执行后端管理操作。



== 删除后端

通过删除 `TridentBackendConfig`，您可以指示Trident删除/保留后端(基于 `deletionPolicy`)。要删除后端、请确保 `deletionPolicy`将设置为delete。要仅删除 `TridentBackendConfig`，请确保 `deletionPolicy`将设置为保留。这样可以确保后端仍然存在，并且可以使用进行管理 `tridentctl`。

运行以下命令：

[listing]
----
kubectl delete tbc <tbc-name> -n trident
----
Trident不会删除正在使用的Kubnetes加密 `TridentBackendConfig`。Kubernetes 用户负责清理密钥。删除机密时必须小心。只有在后端未使用机密时，才应将其删除。



== 查看现有后端

运行以下命令：

[listing]
----
kubectl get tbc -n trident
----
您也可以运行 `tridentctl get backend -n trident` 或 `tridentctl get backend -o YAML -n trident` 来获取存在的所有后端的列表。此列表还将包括使用 `tridentctl` 创建的后端。



== 更新后端

更新后端可能有多种原因：

* 存储系统的凭据已更改。要更新凭据、必须更新对象中使用的Kubbernetes机密 `TridentBackendConfig`。Trident将使用提供的最新凭据自动更新后端。运行以下命令以更新 Kubernetes Secret ：
+
[listing]
----
kubectl apply -f <updated-secret-file.yaml> -n trident
----
* 需要更新参数（例如所使用的 ONTAP SVM 的名称）。
+
** 您可以更新 `TridentBackendConfig` 使用以下命令直接通过KubeNet访问对象：
+
[listing]
----
kubectl apply -f <updated-backend-file.yaml>
----
** 或者、您也可以对现有进行更改 `TridentBackendConfig` 使用以下命令执行CR：
+
[listing]
----
kubectl edit tbc <tbc-name> -n trident
----




[NOTE]
====
* 如果后端更新失败，则后端仍会保持在其上次已知配置中。您可以通过运行 `kubectl get tbc <tbc-name> -o yaml -n trident` 或 `kubectl describe tbc <tbc-name> -n trident` 来查看日志以确定发生原因。
* 确定并更正配置文件中的问题后，您可以重新运行 update 命令。


====