---
sidebar: sidebar 
permalink: trident-use/fcp.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, iscsi, scsi, scsi over fc, fibre channel, fcp, kubernetes clusters, self-healing, healing. 
summary:  
---
= 光纤通道(FC)支持
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
现在、您可以在Trident中使用光纤通道(Fibre Channel、FC)协议来配置和管理ONTAP系统上的存储资源。

*基于光纤通道的SCSI (FC)是Trident 24.10版本中的一项技术预览功能。*

光纤通道因其高性能、可靠性和可扩展性而成为企业存储环境中广泛采用的协议。它为存储设备提供了一个强大而高效的通信通道、可实现快速而安全的数据传输。通过使用基于光纤通道的SCSI、您可以利用现有基于SCSI的存储基础架构、同时享受光纤通道的高性能和远距离功能。它可以整合存储资源、创建可扩展的高效存储区域网络(SAN)、从而以低延迟处理大量数据。

将FC功能与Trident结合使用、您可以执行以下操作：

* 使用部署规范动态配置PVC。
* 创建卷快照并从此快照创建新卷。
* 克隆现有FC-PVC。
* 调整已部署卷的大小。




== 前提条件

为FC配置所需的网络和节点设置。



=== 网络设置

. 获取目标接口的WWPN。有关详细信息、请参见 link:..https://docs.netapp.com/us-en/ontap-cli//network-interface-show.html["network interface show"^] 。
. 获取启动程序(主机)上接口的WWPN。
+
请参阅相应的主机操作系统实用程序。

. 使用主机和目标的WWPN在FC交换机上配置分区。
+
有关信息、请参见相应的交换机供应商文档。

+
有关详细信息、请参见以下ONTAP文档：

+
** https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["光纤通道和 FCoE 分区概述"^]
** https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["配置FC和FC-NVMe SAN主机的方式()"^]






=== 准备工作节点

Kubernetes集群中的所有工作节点都必须能够挂载为Pod配置的卷。要为FC准备工作节点、必须安装所需的工具。

.安装FC工具
使用适用于您的操作系统的命令安装FC工具。

* 使用运行RHEL/RedHat CoreOS和iSCSI PV的工作节点时、请指定 `discard` StorageClass中的mountOption、用于执行实时空间回收。请参见 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Red Hat 文档"^]。


[role="tabbed-block"]
====
.RHEL 8+
--
. 安装以下系统软件包：
+
[listing]
----
sudo yum install -y lsscsi iscsi-initiator-utils device-mapper-multipath
----
. 检查 iscsi-initiator-utils 版本是否为 6.2.0.877-2.el7 或更高版本：
+
[listing]
----
rpm -q iscsi-initiator-utils
----
. 启用多路径：
+
[listing]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 确保 `detc/multipath.conf` contains `find_multipaths no` under` efaults `.

. 确保 `iscsid` 和 `multipathd` 正在运行：
+
[listing]
----
sudo systemctl enable --now iscsid multipathd
----
. 启用并启动 `iSCSI` ：
+
[listing]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. 安装以下系统软件包：
+
[listing]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. 检查 open-iscsi 版本是否为 2.0.877-5ubuntu2.10 或更高版本（对于双子系统）或 2.0.877-7.1ubuntu6.1 或更高版本（对于 Focal ）：
+
[listing]
----
dpkg -l open-iscsi
----
. 将扫描设置为手动：
+
[listing]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. 启用多路径：
+
[listing]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 确保 `detc/multipath.conf` contains `find_multipaths no` under` efaults `.

. 确保已启用并运行 `open-iscsi` 和 `multipath-tools` ：
+
[listing]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----
+

NOTE: 对于 Ubuntu 18.04 ，您必须先使用 `iscsiadm` 发现目标端口，然后再启动 `open-iscsi` ， iSCSI 守护进程才能启动。您也可以将 `iscsi` 服务修改为自动启动 `iscsid` 。



--
====


== 创建后端配置

为驱动程序和 `fcp`创建一个Trident后端 `ontap-san`作为sanType。

请参阅：

* link:..trident-use/ontap-san-prep.html["准备使用ONTAP SAN驱动程序配置后端"]
* link:..trident-use/ontap-san-examples.html["ONTAP SAN配置选项和示例"^]


.使用FC的后端配置示例
[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 10.0.0.1
  sanType: fcp
  svm: trident_svm
  credentials:
    name: backend-tbc-ontap-san-secret
----


== 创建存储类。

有关详细信息、请参见：

* link:..trident-docker/stor-config.html["存储配置选项"^]


.存储类示例
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fcp-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  protocol: "fcp"
  storagePool: "aggr1"
allowVolumeExpansion: True
----