---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: '通过将Trident与Amazon FSx for NetApp ONTAP结合使用、您可以确保在Amazon Elic Kubelnetes Service (EKS)中运行的Kubelnetes集群可以配置ONTAP支持的块和文件永久性卷。' 
---
= 安装 Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident简化了Kubelnetes中适用于NetApp ONTAP的Amazon FSx存储管理、使开发人员和管理员能够专注于应用程序部署。

您可以使用以下方法之一安装Trident：

* 掌舵
* EKS附加项


如果要使用快照功能、请安装CSI快照控制器加载项。有关详细信息、请参见 link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["为CSI卷启用快照功能"^] 。



== 通过舵安装Trident

[role="tabbed-block"]
====
.Pod 身份
--
. 添加 NetApp Trident repo helm 配置：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 使用以下示例安装 Trident：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
您可以使用 `helm list`命令查看安装详细信息、例如名称、命名空间、图表、状态、应用程序版本和修订版号。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.服务帐户协会 (IRSA)
--
. 添加 NetApp Trident repo helm 配置：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 设置“云提供商”和“云身份”的值：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
您可以使用 `helm list`命令查看安装详细信息、例如名称、命名空间、图表、状态、应用程序版本和修订版号。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
如果您计划使用 iSCSI，请确保在客户端计算机上启用了 iSCSI。如果您使用的是 AL2023 工作节点操作系统，则可以通过在 helm 安装中添加 node prep 参数来自动安装 iSCSI 客户端：

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== 通过EKS插件安装Trident

Trident EKS加载项包括最新的安全修补程序和错误修复、并已通过AWS验证、可与Amazon EKS配合使用。通过EKS加载项、您可以始终确保Amazon EKS集群安全稳定、并减少安装、配置和更新加载项所需的工作量。



=== 前提条件

在配置适用于AWS EKS的Trident加载项之前、请确保满足以下条件：

* 具有附加订阅的Amazon EKS集群帐户
* AWS对AWS Marketplace的权限：
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI类型：Amazon Linux 2 (AL2_x86_64)或Amazon Linux 2 ARM (AL2_ARM_64)
* 节点类型：AMD或ARM
* 现有Amazon FSx for NetApp ONTAP文件系统




=== 启用适用于AWS的Trident加载项

[role="tabbed-block"]
====
.管理控制台
--
. 打开Amazon EKS控制台，网址为 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，选择*群集*。
. 选择要为其配置NetApp Trident CSI加载项的集群的名称。
. 选择*Add-ones*，然后选择*Get more add-ones*。
. 请按照以下步骤选择附加组件：
+
.. 向下滚动到 *AWS Marketplace 附加组件* 部分，然后在搜索框中输入 *“Trident”*。
.. 选中 NetApp 的 Trident 框右上角的复选框。
.. 选择 * 下一步 * 。


. 在“*配置选定的附加项*设置”页面上，执行以下操作：
+
.. 选择要使用的*版本*。
.. 如果您使用 IRSA 身份验证，请确保设置可选配置设置中可用的配置值：
+
*** 选择要使用的*版本*。
*** 按照 *附加组件配置模式*，将 *配置值* 部分中的 *configurationValues* 参数设置为您在上一步中创建的角色 ARN（值应采用以下格式）：




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
如果您为冲突解决方法选择覆盖、则可以使用Amazon EKS附加设置覆盖现有附加项的一个或多个设置。如果未启用此选项、并且与现有设置存在冲突、则操作将失败。您可以使用生成的错误消息来解决冲突。在选择此选项之前、请确保Amazon EKS附加组件未管理您需要自行管理的设置。

. 选择“*下一步*”。
. 在*Review and add*页上，选择*Cree*。
+
加载项安装完成后、您将看到已安装的加载项。



--
.AWS命令行界面
--
*1.创建 `add-on.json`文件*：

*对于 Pod Identity，请使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*对于 IRSA 身份验证，请使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: 替换 `<role ARN>`为上一步中创建的角色的ARN。

*2.安装 Trident EKS 插件。*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksc
--
以下示例命令将安装Trident EKS加载项：

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== 更新Trident EKS加载项

[role="tabbed-block"]
====
.管理控制台
--
. 打开Amazon EKS控制台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，选择*群集*。
. 选择要更新NetApp Trident CSI加载项的集群的名称。
. 选择*Add-ones*选项卡。
. 选择* Trident按NetApp显示*，然后选择*编辑*。
. 在“*按NetApp配置Trident”页上，执行以下操作：
+
.. 选择要使用的*版本*。
.. 展开*可选配置设置*并根据需要进行修改。
.. 选择 * 保存更改 * 。




--
.AWS命令行界面
--
以下示例将更新EKS加载项：

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksc
--
* 检查FSxN Trident CSI加载项的当前版本。请替换 `my-cluster`为您的集群名称。
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*示例输出：*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* 将此加载项更新到上一步输出中的update下返回的版本。
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


如果您删除了该 `--force` 选项、并且任何Amazon EKS附加设置与您的现有设置冲突、则更新Amazon EKS附加设置将失败；您将收到一条错误消息、以帮助您解决冲突。在指定此选项之前、请确保Amazon EKS附加组件不会管理您需要管理的设置、因为这些设置会被此选项覆盖。有关此设置的其他选项的详细信息，请参见 link:https://eksctl.io/usage/addons/["插件"]。有关Amazon EKS Kubenetes字段管理的详细信息，请参阅 link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubbernetes现场管理"]。

--
====


=== 卸载/删除Trident EKS加载项

您可以通过两种方式删除Amazon EKS附加项：

* *保留集群上的附加软件*–此选项将删除Amazon EKS对任何设置的管理。此外、它还会使Amazon EKS无法通知您更新、并在您启动更新后自动更新Amazon EKS附加项。但是、它会保留集群上的附加软件。此选项可使附加组件成为自管理安装、而不是Amazon EKS附加组件。通过此选项、此附加组件不会出现停机。保留命令中的 `--preserve` 选项以保留此附加项。
* *从集群中完全删除附加软件*–NetApp建议您仅在集群中没有依赖于此附加软件的资源时、才从集群中删除此附加软件。从命令中删除 `--preserve` 此选项 `delete` 以删除此加载项。



NOTE: 如果此附加项具有关联的IAM帐户、则不会删除此IAM帐户。

[role="tabbed-block"]
====
.管理控制台
--
. 打开Amazon EKS控制台，网址为 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，选择*群集*。
. 选择要删除的NetApp Trident CSI加载项的集群名称。
. 选择*Add-ons*选项卡，然后选择Trident by NetApp。*
. 选择 * 删除 * 。
. 在*Remove NetApp_trdent-operator con確 認*对话框中，执行以下操作：
+
.. 如果您希望Amazon EKS停止管理此附加组件的设置、请选择*保留集群*。如果要在集群上保留附加软件、以便您可以自行管理附加软件的所有设置、请执行此操作。
.. 输入*NetApp_trdent-operator*。
.. 选择 * 删除 * 。




--
.AWS命令行界面
--
请使用集群的名称进行替换 `my-cluster` 、然后运行以下命令。

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksc
--
以下命令将卸载Trident EKS加载项：

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====