---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: 在安装Trident之前、您应查看这些常规系统要求。特定后端可能有其他要求。 
---
= 要求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装Trident之前、您应查看这些常规系统要求。特定后端可能有其他要求。



== 有关Trident的关键信息

*您必须阅读以下有关Trident的重要信息。*

.<strong>与Trident </strong>相关的信息
[%collapsible%open]
====
[]
=====
* Trident现已支持 Kubernetes 1.34。在升级 Kubernetes 之前先升级Trident 。
* Trident会严格强制在SAN环境中使用多路径配置、并在Multipath.conf文件中使用建议值 `find_multipaths: no`。
+
使用非多路径配置或 `find_multipaths: yes` 或 `find_multipaths: smart` multipath.conf文件中的值将导致挂载失败。Trident已建议使用 `find_multipaths: no` 自21.07版起。



=====
====


== 支持的前端（编排程序）

Trident支持多个容器引擎和流程编排程序、其中包括：

* Anthos On－Prem (VMware)和Anthos on Bare metal 1.16
* Kubernetes 1.27 - 1.34
* OpenShift 4.12、4.14 - 4.19（如果您计划使用 OpenShift 4.19 进行 iSCSI 节点准备，则支持的最低Trident版本为 25.06.1。）
+

NOTE: Trident继续支持旧版 OpenShift 版本，与link:https://access.redhat.com/support/policy/updates/openshift["Red Hat 扩展更新支持 (EUS) 发布生命周期"]，即使它们依赖上游不再受官方支持的 Kubernetes 版本。在这种情况下安装Trident时，您可以放心地忽略有关 Kubernetes 版本的任何警告消息。

* Rancher Kubernetes Engine 2（RKE2）v1.27.x - 1.34.x
+

NOTE: 虽然Trident在 Rancher Kubernetes Engine 2 (RKE2) 版本 1.27.x - 1.34.x 上受支持，但Trident目前仅在 RKE2 v1.28.5+rke2r1 上获得认证。



Trident还可以与许多其他完全托管和自行管理的Kubernetes产品配合使用、包括Google Kubernetes Engine (GKE)、Amazon Elatic Kubernetes Services (EKS)、Azure Kubernetes Service (AKS)、MiranT斯Kubernetes Engine (MKE)和VMware Tanzu产品组合。

Trident和ONTAP可用作的存储提供程序link:https://kubevirt.io/["KubeVirt"]。


WARNING: 在将安装了Trident的Kubernetes集群从1.25升级到1.26或更高版本之前，请参见link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["升级Helm安装"]。



== 支持的后端（存储）

要使用Trident、您需要使用以下一个或多个受支持的后端：

* 适用于 NetApp ONTAP 的 Amazon FSX
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp卷
* NetApp 全 SAN 阵列（ ASA ）
* NetApp 有限支持下的本地FAS、 AFF、Select 或ASA r2（iSCSI 和 NVMe/TCP）集群版本。看link:https://mysupport.netapp.com/site/info/version-support["软件版本支持"]。
* NetApp HCI/ Element软件11或更高版本




== Trident支持KubeVirt和OpenShift虚拟化

.支持的存储驱动程序：
Trident支持以下用于KubeVirt和OpenShift虚拟化的ONTAP驱动程序：

* ontap-NAS
* ONTAP—NAS—经济型
* NVMe-SAN (iSCSI、FCP、基于的ONTAP)
* ONTAP—SAN经济型(仅限iSCSI)


.注意事项：
* 在OpenShift虚拟化环境中更新存储类以使用 `fsType`参数(例如： `fsType: "ext4"`)。如果需要、可使用中的参数 `dataVolumeTemplates`将卷模式明确设置为阻止 `volumeMode=Block`、以通知数据卷创建者。
* _rwx块存储驱动程序访问模式_：只有"volumemode：block"(原始设备)才支持ONTAP SAN (iSCSI、NVMe/TCP、FC)和ONTAP SAN经济型(iSCSI)驱动程序。对于这些驱动程序、 `fstype`无法使用参数、因为卷是在原始设备模式下提供的。
* 对于需要rwx访问模式的实时迁移工作流、支持以下组合：
+
** NFS + `volumeMode=Filesystem`
** iSCSI + `volumeMode=Block`(原始设备)
** NVMe/TCP + `volumeMode=Block`(原始设备)
** FC + `volumeMode=Block`(原始设备)






== 功能要求

下表总结了此版本的Trident及其支持的Kubernetes版本提供的功能。

[cols="3"]
|===
| 功能 | Kubernetes 版本 | 是否需要功能安全门？ 


| Trident  a| 
1.27 - 1.34
 a| 
否



| 卷快照  a| 
1.27 - 1.34
 a| 
否



| 卷快照中的 PVC  a| 
1.27 - 1.34
 a| 
否



| iSCSI PV 调整大小  a| 
1.27 - 1.34
 a| 
否



| ONTAP 双向 CHAP  a| 
1.27 - 1.34
 a| 
否



| 动态导出策略  a| 
1.27 - 1.34
 a| 
否



| Trident 运算符  a| 
1.27 - 1.34
 a| 
否



| CSI 拓扑  a| 
1.27 - 1.34
 a| 
否

|===


== 已测试主机操作系统

虽然Trident不正式支持特定操作系统、但已知以下操作系统可以正常工作：

* OpenShift容器平台(amd64和ARM64)支持的Red Hat Enterprise Linux CoreTM OS (RHCOS)版本
* RHEL 8+(AMD64和ARM64)
+

NOTE: NVMe/TCP需要RHEL 9或更高版本。

* Ubuntu 22.04或更高版本(AMD64和ARM64)
* Windows Server 2022


默认情况下、Trident在容器中运行、因此将在任何Linux工作器上运行。但是、根据您使用的后端、这些员工需要能够使用标准NFS客户端或iSCSI启动程序挂载Trident提供的卷。

`tridentctl` 实用程序也可在 Linux 的任何这些分发版上运行。



== 主机配置

Kubernetes集群中的所有工作节点都必须能够挂载为Pod配置的卷。要准备工作节点、必须根据您选择的驱动程序安装NFS、iSCSI或NVMe工具。

link:../trident-use/worker-node-prep.html["准备工作节点"]



== 存储系统配置：

Trident可能需要先对存储系统进行更改、然后后端配置才能使用它。

link:../trident-use/backends.html["配置后端"]



== Trident端口

Trident需要访问特定端口才能进行通信。

link:../trident-reference/ports.html["Trident端口"]



== 容器映像以及相应的 Kubernetes 版本

对于气隙安装、以下列表是安装Trident所需容器映像的参考。使用 `tridentctl images`命令验证所需容器映像的列表。



=== Trident 25.06.2 所需的容器镜像

[cols="2"]
|===
| Kubernetes版本 | 容器映像 


| v1.27.0、v1.28.0、v1.29.0、v1.30.0、v1.31.0、v1.32.0、v1.33.0、v1.34.0  a| 
* docker.io/netapp/trident:25.06.2
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
* docker.io/netapp/trident-operator:25.06.2（可选）


|===


=== Trident 25.06 所需的容器镜像

[cols="2"]
|===
| Kubernetes版本 | 容器映像 


| v1.27.0、v1.28.0、v1.29.0、v1.30.0、v1.31.0、v1.32.0、v1.33.0、v1.34.0  a| 
* docker.io/netapp/trident:25.06.0
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
* docker.io/netapp/trident-operator:25.06.0（可选）


|===