---
sidebar: sidebar 
permalink: trident-protect/trident-protect-use-snapmirror-replication.html 
keywords: trident, protect, netapp, snapmirror, data, asynchronous, replication, clusters 
summary: 通过使用Trident Protect、您可以使用NetApp SnapMirror技术的异步复制功能将数据和应用程序更改从一个存储后端复制到另一个存储后端、复制到同一集群上或复制到不同集群之间。 
---
= 使用NetApp SnapMirror和Trident Protect复制应用程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
通过使用Trident Protect、您可以使用NetApp SnapMirror技术的异步复制功能将数据和应用程序更改从一个存储后端复制到另一个存储后端、复制到同一集群上或复制到不同集群之间。



== 还原和故障转移操作期间的命名空间标注和标签

在还原和故障转移操作期间、目标命名空间中的标签和标注会与源命名空间中的标签和标注相匹配。此时将添加源命名空间中目标命名空间中不存在的标签或标注、并覆盖已存在的任何标签或标注、以便与源命名空间中的值匹配。仅存在于目标命名空间上的标签或标注保持不变。


NOTE: 如果您使用 Red Hat OpenShift，请务必注意命名空间注释在 OpenShift 环境中的重要作用。命名空间注释确保恢复的 pod 遵守 OpenShift 安全上下文约束 (SCC) 定义的适当权限和安全配置，并且可以访问卷而不会出现权限问题。欲了解更多信息，请参阅link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift安全上下文约束文档"^]。

在执行还原或故障转移操作之前、您可以通过设置Kubornetes环境变量来防止目标命名空间中的特定标注被覆盖 `RESTORE_SKIP_NAMESPACE_ANNOTATIONS`。例如：

[source, console]
----
helm upgrade trident-protect --set restoreSkipNamespaceAnnotations=<annotation_key_to_skip_1>,<annotation_key_to_skip_2> --reuse-values
----

NOTE: 执行恢复或故障转移操作时，任何命名空间注释和标签都将生效。 `restoreSkipNamespaceAnnotations` 和 `restoreSkipNamespaceLabels` 不参与恢复或故障转移操作。确保在初始 Helm 安装期间配置这些设置。欲了解更多信息，请参阅 link:../trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["配置其他Trident保护 Helm Chart 设置"]。

如果您使用带有标志的Helm安装源应用程序，则会对标签键进行 `--create-namespace`特殊处理 `name`。在还原或故障转移过程中、Trident Protect会将此标签复制到目标命名空间、但如果源命名空间中的值与源命名空间匹配、则会将此值更新为目标命名空间值。如果此值与源命名空间不匹配、则会将其复制到目标命名空间、而不会发生任何更改。



=== 示例

以下示例显示了一个源和目标命名空间、每个命名空间都具有不同的标注和标签。您可以查看目标命名空间在操作前后的状态、以及标注和标签在目标命名空间中的组合或覆盖方式。



==== 在执行还原或故障转移操作之前

下表说明了执行还原或故障转移操作之前示例源和目标名称卷的状态：

[cols="1,2a,2a"]
|===
| 命名空间 | 标注 | 标签 


| 命名空间ns-1 (源)  a| 
* 标注.One/键："updatedvalue"
* 标注。双/键："TRUE"

 a| 
* 环境=生产
* 合规性=HIPAA
* name=ns-1




| 命名空间ns-2 (目标)  a| 
* 标注.One/键："TRUE"
* 标注三个/项："false"

 a| 
* Role=database


|===


==== 还原操作之后

下表显示了还原或故障转移操作后示例目标命名空间的状态。已添加某些密钥、某些密钥已被覆盖、并且 `name`标签已更新以与目标命名空间匹配：

[cols="1,2a,2a"]
|===
| 命名空间 | 标注 | 标签 


| 命名空间ns-2 (目标)  a| 
* 标注.One/键："updatedvalue"
* 标注。双/键："TRUE"
* 标注三个/项："false"

 a| 
* name=nS-2
* 合规性=HIPAA
* 环境=生产
* Role=database


|===

NOTE: 您可以将Trident Protect配置为在数据保护操作期间冻结和取消冻结文件系统。link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["详细了解如何使用Trident Protect配置文件系统冻结"](英文)



== 故障转移和反向操作期间的执行挂钩

当使用 AppMirror 关系保护您的应用程序时，您应该在故障转移和反转操作期间注意与执行挂钩相关的特定行为。

* 在故障转移期间，执行挂钩会自动从源集群复制到目标集群。您无需手动重新创建它们。故障转移后，执行挂钩仍存在于应用程序中，并将在任何相关操作期间执行。
* 在反向同步或反向重新同步期间，应用程序上所有现有的执行钩子都将被移除。当源应用程序成为目标应用程序时，这些执行钩子将失效，并会被删除以阻止其执行。


要了解有关执行钩子的更多信息，请参阅link:../trident-protect/trident-protect-use-execution-hooks.html["管理Trident Protect执行挂钩"] 。



== 设置复制关系

设置复制关系涉及以下方面：

* 选择希望Trident Protect创建应用程序快照的频率(包括应用程序的Kubbernetes资源以及应用程序每个卷的卷快照)
* 选择复制计划(包括Kubbernetes资源以及永久性卷数据)
* 设置创建快照的时间


.步骤
. 在源集群上、为源应用程序创建AppVault。根据您的存储提供程序、修改中的示例link:trident-protect-appvault-custom-resources.html["AppVault自定义资源"]以适合您的环境：
+
[role="tabbed-block"]
====
.使用CR创建AppVault
--
.. 创建自定义资源(CR)文件并将其命名(例如 `trident-protect-appvault-primary-source.yaml`)。
.. 配置以下属性：
+
*** * metadata.name*:(_required__) AppVault自定义资源的名称。请记下您选择的名称、因为复制关系所需的其他CR文件会引用此值。
*** *。spec.providerConfig*:(_required__)存储使用指定提供程序访问AppVault所需的配置。为您的提供商选择一个BucketName和任何其他必要的详细信息。请记下所选的值、因为复制关系所需的其他CR文件会引用这些值。有关其他提供商的AppVault CRS示例、请参见link:trident-protect-appvault-custom-resources.html["AppVault自定义资源"]。
*** *。spec.providerCredentials*:(_required__)存储对使用指定提供程序访问AppVault所需的任何凭据的引用。
+
**** *。spec.providerCredentials.valueFromSecret*:(_required__)表示凭据值应来自密钥。
+
***** *key*:(_required_)要从中选择的密钥的有效密钥。
***** *name*:(_required_)包含此字段值的机密的名称。必须位于同一命名空间中。


**** * spec.providerCredentials.secretAccessKey*:(_required__)用于访问提供程序的访问密钥。名称*应与*。spec.providerCredentials.valueFromSecret.name*。


*** *。spec.providerType*:(_required__)用于确定提供备份的内容；例如、NetApp ONTAP S3、通用S3、Google Cloud或Microsoft Azure。可能值：
+
**** aws
**** azure
**** GCP
**** 常规S3
**** ONTAP S3
**** StorageGRID S3




.. 使用正确的值填充文件后 `trident-protect-appvault-primary-source.yaml` 、应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-appvault-primary-source.yaml -n trident-protect
----


--
.使用命令行界面创建AppVault
--
.. 创建AppVault、将括号中的值替换为您环境中的信息：
+
[source, console]
----
tridentctl-protect create vault Azure <vault-name> --account <account-name> --bucket <bucket-name> --secret <secret-name> -n trident-protect
----


--
====
. 在源集群上、创建源应用程序CR：
+
[role="tabbed-block"]
====
.使用CR创建源应用程序
--
.. 创建自定义资源(CR)文件并将其命名(例如 `trident-protect-app-source.yaml`)。
.. 配置以下属性：
+
*** *metadata.name*:(_required__)应用程序自定义资源的名称。请记下您选择的名称、因为复制关系所需的其他CR文件会引用此值。
*** *。spec.includedNamespaces*:(_required__)一个由命名区域和关联标签组成的数组。使用命名空间名称、并可选择通过标签缩小命名空间的范围、以指定此处列出的命名空间中存在的资源。应用程序命名空间必须属于此数组。
+
*示例YAML*：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: my-app-name
  namespace: my-app-namespace
spec:
  includedNamespaces:
    - namespace: my-app-namespace
      labelSelector: {}
----


.. 使用正确的值填充文件后 `trident-protect-app-source.yaml` 、应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-app-source.yaml -n my-app-namespace
----


--
.使用命令行界面创建源应用程序
--
.. 创建源应用程序。例如：
+
[source, console]
----
tridentctl-protect create app <my-app-name> --namespaces <namespaces-to-be-included> -n <my-app-namespace>
----


--
====
. （可选）在源集群上，对源应用程序进行快照。此快照将用作目标集群上应用程序的基础。如果跳过此步骤，则需要等待下一次计划快照运行，以便获得最新的快照。要创建按需快照，请参阅 link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html#create-an-on-demand-snapshot["创建按需快照"^]。
. 在源集群上，创建复制计划 CR：
+
[NOTE]
====
除了下面提供的计划外，建议创建一个单独的每日快照计划，保留期为 7 天，以便在对等 ONTAP 集群之间维护通用快照。这可确保快照最多可用 7 天，但保留期可根据用户需求自定义。

如果发生故障转移，系统可以使用这些快照最多 7 天进行反向操作。这种方法使反向过程更快、更高效，因为只会传输自上次快照以来所做的更改，而不是所有数据。

如果应用程序的现有计划已经满足所需的保留要求，则不需要额外的计划。

====
+
[role="tabbed-block"]
====
.使用 CR 创建复制计划
--
.. 为源应用程序创建复制计划：
+
... 创建自定义资源(CR)文件并将其命名(例如 `trident-protect-schedule.yaml`)。
... 配置以下属性：
+
**** * metadata.name*:(_required__)计划自定义资源的名称。
**** *spec.appVaultRef*: (_必需_) 此值必须与源应用程序的 AppVault 的 metadata.name 字段匹配。
**** *spec.applicationRef*: (_必需_) 此值必须与源应用程序 CR 的 metadata.name 字段匹配。
**** *spec.backup놣 쇴*：(_required_)此字段为必填字段、且值必须设置为0。
**** *spec.enabled *：必须设置为true。
**** *。spec.granularity*:必须设置为 `Custom`。
**** *spec.rec发 规则*：定义UTC时间的开始日期和重复间隔。
**** *spec.snapshot놣 쇴*：必须设置为2。
+
YAML示例：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: appmirror-schedule
  namespace: my-app-namespace
spec:
  appVaultRef: my-appvault-name
  applicationRef: my-app-name
  backupRetention: "0"
  enabled: true
  granularity: Custom
  recurrenceRule: |-
    DTSTART:20220101T000200Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  snapshotRetention: "2"
----


... 使用正确的值填充文件后 `trident-protect-schedule.yaml` 、应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-schedule.yaml -n my-app-namespace
----




--
.使用 CLI 创建复制计划
--
.. 创建复制计划，并将括号中的值替换为您环境中的信息：
+
[source, console]
----
tridentctl-protect create schedule --name appmirror-schedule --app <my_app_name> --appvault <my_app_vault> --granularity Custom --recurrence-rule <rule> --snapshot-retention <snapshot_retention_count> -n <my_app_namespace>
----
+
* 示例： *

+
[source, console]
----
tridentctl-protect create schedule --name appmirror-schedule --app <my_app_name> --appvault <my_app_vault> --granularity Custom --recurrence-rule  "DTSTART:20220101T000200Z\nRRULE:FREQ=MINUTELY;INTERVAL=5" --snapshot-retention 2 -n <my_app_namespace>
----


--
====
. 在目标集群上，创建一个与您在源集群上应用的AppVault CR完全相同的源应用程序AppVault CR，并将其命名为(例如 `trident-protect-appvault-primary-destination.yaml`)。
. 应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-appvault-primary-destination.yaml -n trident-protect
----
. 在目标集群上为目标应用程序创建目标AppVault CR。根据您的存储提供程序、修改中的示例link:trident-protect-appvault-custom-resources.html["AppVault自定义资源"]以适合您的环境：
+
.. 创建自定义资源(CR)文件并将其命名(例如 `trident-protect-appvault-secondary-destination.yaml`)。
.. 配置以下属性：
+
*** * metadata.name*:(_required__) AppVault自定义资源的名称。请记下您选择的名称、因为复制关系所需的其他CR文件会引用此值。
*** *。spec.providerConfig*:(_required__)存储使用指定提供程序访问AppVault所需的配置。为您的提供商选择 `bucketName`以及任何其他必要的详细信息。请记下所选的值、因为复制关系所需的其他CR文件会引用这些值。有关其他提供商的AppVault CRS示例、请参见link:trident-protect-appvault-custom-resources.html["AppVault自定义资源"]。
*** *。spec.providerCredentials*:(_required__)存储对使用指定提供程序访问AppVault所需的任何凭据的引用。
+
**** *。spec.providerCredentials.valueFromSecret*:(_required__)表示凭据值应来自密钥。
+
***** *key*:(_required_)要从中选择的密钥的有效密钥。
***** *name*:(_required_)包含此字段值的机密的名称。必须位于同一命名空间中。


**** * spec.providerCredentials.secretAccessKey*:(_required__)用于访问提供程序的访问密钥。名称*应与*。spec.providerCredentials.valueFromSecret.name*。


*** *。spec.providerType*:(_required__)用于确定提供备份的内容；例如、NetApp ONTAP S3、通用S3、Google Cloud或Microsoft Azure。可能值：
+
**** aws
**** azure
**** GCP
**** 常规S3
**** ONTAP S3
**** StorageGRID S3




.. 使用正确的值填充文件后 `trident-protect-appvault-secondary-destination.yaml` 、应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-appvault-secondary-destination.yaml -n trident-protect
----


. 在目标集群上、创建App镜像 关系CR文件：
+
[role="tabbed-block"]
====
.使用CR创建App镜像 关系
--
.. 创建自定义资源(CR)文件并将其命名(例如 `trident-protect-relationship.yaml`)。
.. 配置以下属性：
+
*** * metadata.name:*(必需) App镜像 关系自定义资源的名称。
*** *。spec.destinationAppVaultRef*:(_required__)此值必须与目标集群上目标应用程序的AppVault名称匹配。
*** *。spec.namespaceMapping*:(_required__)目标和源命名空间必须与相应应用程序CR中定义的应用程序命名空间匹配。
*** *spec.sourceAppVaultRef*：(_required_)此值必须与源应用程序的AppVault名称匹配。
*** *spec.sourceApplicationName*:(_required_)此值必须与您在源应用程序CR中定义的源应用程序的名称匹配。
*** *spec.sourceApplicationUID*: （必需）此值必须与您在源应用程序 CR 中定义的源应用程序的 UID 匹配。
*** *spec.storageClassName*: (_可选_) 选择集群上有效的存储类的名称。存储类必须链接到与源环境建立对等连接的ONTAP存储 VM。如果未提供存储类，则默认使用集群上的默认存储类。
*** *spec.rec发 规则*：定义UTC时间的开始日期和重复间隔。
+
YAML示例：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AppMirrorRelationship
metadata:
  name: amr-16061e80-1b05-4e80-9d26-d326dc1953d8
  namespace: my-app-namespace
spec:
  desiredState: Established
  destinationAppVaultRef: generic-s3-trident-protect-dst-bucket-8fe0b902-f369-4317-93d1-ad7f2edc02b5
  namespaceMapping:
    - destination: my-app-namespace
      source: my-app-namespace
  recurrenceRule: |-
    DTSTART:20220101T000200Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  sourceAppVaultRef: generic-s3-trident-protect-src-bucket-b643cc50-0429-4ad5-971f-ac4a83621922
  sourceApplicationName: my-app-name
  sourceApplicationUID: 7498d32c-328e-4ddd-9029-122540866aeb
  storageClassName: sc-vsim-2
----


.. 使用正确的值填充文件后 `trident-protect-relationship.yaml` 、应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-relationship.yaml -n my-app-namespace
----


--
.使用命令行界面创建App镜像 关系
--
.. 创建并应用 AppMirrorRelationship 对象，并将括号中的值替换为您环境中的信息：
+
[source, console]
----
tridentctl-protect create appmirrorrelationship <name_of_appmirorrelationship> --destination-app-vault <my_vault_name> --source-app-vault <my_vault_name> --recurrence-rule <rule> --namespace-mapping <ns_mapping> --source-app-id <source_app_UID> --source-app <my_source_app_name> --storage-class <storage_class_name> -n <application_namespace>
----
+
* 示例： *

+
[source, console]
----
tridentctl-protect create appmirrorrelationship my-amr --destination-app-vault appvault2 --source-app-vault appvault1 --recurrence-rule "DTSTART:20220101T000200Z\nRRULE:FREQ=MINUTELY;INTERVAL=5" --source-app my-app --namespace-mapping "my-source-ns1:my-dest-ns1,my-source-ns2:my-dest-ns2" --source-app-id 373f24c1-5769-404c-93c3-5538af6ccc36 --storage-class my-storage-class -n my-dest-ns1
----


--
====
. (_可 选_)在目标集群上、检查复制关系的状态：
+
[source, console]
----
kubectl get amr -n my-app-namespace <relationship name> -o=jsonpath='{.status}' | jq
----




=== 故障转移到目标集群

使用Trident Protect、您可以将复制的应用程序故障转移到目标集群。此操作步骤 将停止复制关系并使应用程序在目标集群上联机。如果源集群上的应用程序正常运行、则Trident Protect不会停止该应用程序。

.步骤
. 在目标集群上，编辑AppMirorRelationship CR文件(例如 `trident-protect-relationship.yaml`)，并将*spec.desiredState*的值更改为 `Promoted`。
. 保存 CR 文件。
. 应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-relationship.yaml -n my-app-namespace
----
. (_可 选_)在故障转移应用程序上创建所需的任何保护计划。
. (_可 选_)检查复制关系的状态：
+
[source, console]
----
kubectl get amr -n my-app-namespace <relationship name> -o=jsonpath='{.status}' | jq
----




=== 重新同步故障转移复制关系

重新同步操作将重新建立复制关系。执行重新同步操作后、原始源应用程序将成为正在运行的应用程序、对目标集群上正在运行的应用程序所做的任何更改将被丢弃。

此过程会先停止目标集群上的应用程序、然后再重新建立复制。


IMPORTANT: 故障转移期间写入目标应用程序的所有数据都将丢失。

.步骤
. 可选：在源集群上、创建源应用程序的快照。这样可确保捕获源集群的最新更改。
. 在目标集群上，编辑AppMirorRelationship CR文件(例如 `trident-protect-relationship.yaml`)，并将spec.desiredState的值更改为 `Established`。
. 保存 CR 文件。
. 应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-relationship.yaml -n my-app-namespace
----
. 如果您在目标集群上创建了任何保护计划来保护故障转移应用程序、请将其删除。任何保留的计划都会导致卷快照失败。




=== 反向重新同步故障转移复制关系

反向重新同步故障转移复制关系时、目标应用程序将成为源应用程序、而源将成为目标。在故障转移期间对目标应用程序所做的更改将保留下来。

.步骤
. 在初始目标集群上、删除App镜像 关系CR。这会使目标成为源。如果新目标集群上仍有任何保护计划、请将其删除。
. 通过将最初用于设置复制关系的CR文件应用于对等集群来设置复制关系。
. 确保为新目标(初始源集群)配置了两个AppVault CRS。
. 在另一个集群上设置复制关系、并配置反向值。




== 反转应用程序复制方向

反向复制方向时、Trident Protect会将应用程序移至目标存储后端、同时继续复制回原始源存储后端。Trident Protect会先停止源应用程序并将数据复制到目标、然后再故障转移到目标应用程序。

在这种情况下、您将交换源和目标。

.步骤
. 在源集群上、创建一个关闭快照：
+
[role="tabbed-block"]
====
.使用CR创建关闭快照
--
.. 禁用源应用程序的保护策略计划。
.. 创建Sh关机Snapshot CR文件：
+
... 创建自定义资源(CR)文件并将其命名(例如 `trident-protect-shutdownsnapshot.yaml`)。
... 配置以下属性：
+
**** * metadata.name*:(_required__)自定义资源的名称。
**** *spec.appVaultRef*：(_required_)此值必须与源应用程序的AppVault的metadata.name字段匹配。
**** *spec.ApplicationRef*：(_required_)此值必须与源应用程序CR文件的metadata.name字段匹配。
+
YAML示例：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: ShutdownSnapshot
metadata:
  name: replication-shutdown-snapshot-afc4c564-e700-4b72-86c3-c08a5dbe844e
  namespace: my-app-namespace
spec:
  appVaultRef: generic-s3-trident-protect-src-bucket-04b6b4ec-46a3-420a-b351-45795e1b5e34
  applicationRef: my-app-name
----




.. 使用正确的值填充文件后 `trident-protect-shutdownsnapshot.yaml` 、应用CR：
+
[source, console]
----
kubectl apply -f trident-protect-shutdownsnapshot.yaml -n my-app-namespace
----


--
.使用命令行界面创建关闭快照
--
.. 创建关闭快照、将括号中的值替换为环境中的信息。例如：
+
[source, console]
----
tridentctl-protect create shutdownsnapshot <my_shutdown_snapshot> --appvault <my_vault> --app <app_to_snapshot> -n <application_namespace>
----


--
====
. 在源集群上、关闭快照完成后、获取关闭快照的状态：
+
[source, console]
----
kubectl get shutdownsnapshot -n my-app-namespace <shutdown_snapshot_name> -o yaml
----
. 在源集群上，使用以下命令查找*shutdownfapp.statues.appArchivePath*的值，并记录文件路径的最后一部分(也称为基本名称；这将是最后一个斜杠之后的所有内容)：
+
[source, console]
----
k get shutdownsnapshot -n my-app-namespace <shutdown_snapshot_name> -o jsonpath='{.status.appArchivePath}'
----
. 执行从新目标集群到新源集群的故障转移、并进行以下更改：
+

NOTE: 在故障转移过程的第2步中、将字段包含 `spec.promotedSnapshot`在App镜像 关系CR文件中、并将其值设置为您在上述第3步中记录的基本名称。

. 执行中的反向重新同步步骤<<反向重新同步故障转移复制关系>>。
. 在新的源集群上启用保护计划。




=== 结果

反向复制会导致以下操作：

* 系统会为原始源应用程序的Kubbernetes资源创建一个快照。
* 通过删除原始源应用程序的Kubernetes资源(保留PVC和PV)、可以正常停止原始源应用程序的Pod。
* 关闭Pod后、将为应用程序的卷创建快照并进行复制。
* SnapMirror关系将中断、从而使目标卷做好读/写准备。
* 此应用程序的Kubornetes资源将使用在初始源应用程序关闭后复制的卷数据从关闭前的快照中还原。
* 反向重新建立复制。




=== 将应用程序故障恢复到原始源集群

通过使用Trident Protect、您可以通过以下操作序列在故障转移操作后实现"故障恢复"。在此恢复原始复制方向的工作流中、Trident Protect会在反转复制方向之前将所有应用程序更改复制(重新同步)回原始源应用程序。

此过程从已完成故障转移到目标的关系开始、涉及以下步骤：

* 从故障转移状态开始。
* 反向重新同步复制关系。
+

CAUTION: 请勿执行正常的重新同步操作、因为这会丢弃在故障转移过程中写入目标集群的数据。

* 反转复制方向。


.步骤
. 执行<<反向重新同步故障转移复制关系>>步骤。
. 执行<<反转应用程序复制方向>>步骤。




=== 删除复制关系

您可以随时删除复制关系。删除应用程序复制关系后、会导致两个单独的应用程序之间没有关系。

.步骤
. 在当前目标集群上、删除App镜像 关系CR：
+
[source, console]
----
kubectl delete -f trident-protect-relationship.yaml -n my-app-namespace
----

