---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: 自定义Trident Protect 的默认设置，以满足您的特定需求。 
---
= 定制Trident Protect 安装
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自定义Trident Protect 的默认配置，以满足您环境的特定要求。



== 指定Trident Protect 容器资源限制

安装Trident Protect 后，您可以使用配置文件来指定Trident Protect 容器的资源限制。设置资源限制可以控制Trident Protect 操作消耗集群资源的程度。

.步骤
. 创建一个名为的文件 `resourceLimits.yaml`。
. 根据您的环境需求，在文件中填充Trident Protect 容器的资源限制选项。
+
以下示例配置文件显示了可用设置、并包含每个资源限制的默认值：

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. 应用文件中的值 `resourceLimits.yaml`：
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== 自定义安全上下文约束

安装Trident Protect 后，您可以使用配置文件来修改Trident Protect 容器的 OpenShift 安全上下文约束 (SCC)。这些约束定义了 Red Hat OpenShift 集群中 pod 的安全限制。

.步骤
. 创建一个名为的文件 `sccconfig.yaml`。
. 将scc选项添加到文件中、然后根据环境的需要修改参数。
+
以下示例显示了SCC选项参数的默认值：

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
下表介绍了SCC选项的参数：

+
|===
| 参数 | Description | Default 


| 创建 | 确定是否可以创建SCC资源。只有在将设置为 `true`且Helm安装过程标识OpenShift环境时、才会创建SCC资源 `scc.create`。如果不在OpenShift上运行，或者如果 `scc.create`设置为 `false`，则不会创建任何SCC资源。 | true 


| name | 指定SCC的名称。 | Trident保护作业 


| 优先级 | 定义SCC的优先级。优先级值较高的SCC会在优先级值较低的SCC之前进行评估。 | 1 
|===
. 应用文件中的值 `sccconfig.yaml`：
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
此操作会将默认值替换为文件中指定的值 `sccconfig.yaml`。





== 配置其他Trident Protect 舵图设置

您可以自定义AutoSupport设置和命名空间过滤以满足您的特定要求。下表描述了可用的配置参数：

|===
| 参数 | Type | Description 


| 自动支持代理 | string | 为NetApp AutoSupport连接配置代理 URL。使用此功能通过代理服务器路由支持包上传。例子： `http://my.proxy.url` 。 


| 自动支持.不安全 | boolean | 设置为时跳过AutoSupport代理连接的 TLS 验证 `true`。仅用于不安全的代理连接。  （默认： `false` ) 


| 自动支持已启用 | boolean | 启用或禁用每日Trident Protect AutoSupport捆绑包上传。设置为 `false`每日定时上传功能已禁用，但您仍然可以手动生成支持包。（默认： `true` ） 


| 恢复跳过命名空间注释 | string | 要从备份和恢复操作中排除的命名空间注释的逗号分隔列表。允许您根据注释过滤命名空间。 


| restoreSkipNamespaceLabels | string | 要从备份和恢复操作中排除的命名空间标签的逗号分隔列表。允许您根据标签过滤命名空间。 
|===
您可以使用 YAML 配置文件或命令行标志配置这些选项：

[role="tabbed-block"]
====
.使用 YAML 文件
--
.步骤
. 创建配置文件并命名 `values.yaml`。
. 在您创建的文件中，添加您想要自定义的配置选项。
+
[source, console]
----
autoSupport:
  enabled: false
  proxy: http://my.proxy.url
  insecure: true
restoreSkipNamespaceAnnotations: "annotation1,annotation2"
restoreSkipNamespaceLabels: "label1,label2"
----
. 填充后 `values.yaml`具有正确值的文件，应用配置文件：
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f values.yaml --reuse-values
----


--
.使用 CLI 标志
--
.步骤
. 使用以下命令 `--set`标志来指定单个参数：
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set autoSupport.enabled=false \
  --set autoSupport.proxy=http://my.proxy.url \
  --set restoreSkipNamespaceAnnotations="annotation1,annotation2" \
  --set restoreSkipNamespaceLabels="label1,label2" \
  --reuse-values
----


--
====


== 将Trident Protect Pod 限制在特定节点上

您可以使用 Kubernetes nodeSelector 节点选择约束，根据节点标签来控制哪些节点有资格运行Trident Protect pod。默认情况下， Trident Protect 仅限于运行 Linux 的节点。您可以根据需要进一步自定义这些限制条件。

.步骤
. 创建一个名为的文件 `nodeSelectorConfig.yaml`。
. 将nodeSelector选项添加到文件中、然后修改文件以添加或更改节点标签、从而根据环境需求进行限制。例如、以下文件包含默认操作系统限制、但也针对特定区域和应用程序名称：
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. 应用文件中的值 `nodeSelectorConfig.yaml`：
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
此操作会将默认限制替换为您在文件中指定的限制 `nodeSelectorConfig.yaml`。


