---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 首先验证您的操作环境、应用程序集群、应用程序和许可证是否已准备就绪。确保您的环境满足这些要求、才能部署和运行Trident Protect。 
---
= Trident Protect要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
首先验证您的操作环境、应用程序集群、应用程序和许可证是否已准备就绪。确保您的环境满足这些要求、才能部署和运行Trident Protect。



== Trident Protect Kubbernetes集群兼容性

Trident Protect与各种完全托管和自行管理的Kubernetes产品兼容、其中包括：

* Amazon Elelic Kubelnetes Service (EKS)
* Google Kubernetes Engine （ GKEE ）
* Microsoft Azure Kubernetes Service （ AKS ）
* Red Hat OpenShift
* SUSE试用者
* VMware Tanzu产品组合
* 上游Kubernetes


[NOTE]
====
* Trident保护备份仅支持 Linux 计算节点。  Windows 计算节点不支持备份操作。
* 确保为安装Trident Protect的集群配置了正在运行的快照控制器以及相关的CRD。要安装快照控制器，请参见 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["这些说明"]。


====


== Trident保护存储后端兼容性

Trident Protect支持以下存储后端：

* 适用于 NetApp ONTAP 的 Amazon FSX
* Cloud Volumes ONTAP
* ONTAP存储阵列
* Google Cloud NetApp卷
* Azure NetApp Files


确保存储后端满足以下要求：

* 确保连接到集群的 NetApp 存储使用 Trident 24.02 或更新版本（建议使用 Trident 24.10）。


* 确保您有一个NetApp ONTAP存储后端。
* 确保已配置用于存储备份的对象存储分段。
* 创建您计划用于应用程序或应用程序数据管理操作的任何应用程序卷。Trident Protect不会为您创建这些命名空间；如果在自定义资源中指定不存在的命名空间、则操作将失败。




== NAS经济型卷的要求

Trident Protect支持对NAS经济型卷执行备份和还原操作。目前不支持将快照、克隆和SnapMirror复制到NAS经济型卷。您需要为计划与Trident Protect结合使用的每个NAS经济型卷启用一个Snapshot目录。

[NOTE]
====
某些应用程序与使用Snapshot目录的卷不兼容。对于这些应用程序、您需要通过在ONTAP存储系统上运行以下命令来隐藏Snapshot目录：

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
您可以通过对每个NAS经济型卷运行以下命令来启用Snapshot目录、并将其替换 `<volume-UUID>`为要更改的卷的UUID：

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: 通过将Trident后端配置选项设置为，您可以默认为 `true`新卷启用快照目录 `snapshotDir`。现有卷不受影响。



== 使用KubeVirt VM保护数据

保护在KubeVirt VM上运行的应用程序时、Trident Protect 24.10 24.10.1及更高版本的行为会有所不同。对于这两个版本、您都可以在数据保护操作期间启用或禁用文件系统冻结和解除冻结。


NOTE: 在恢复操作期间，任何 `VirtualMachineSnapshots`为虚拟机 (VM) 创建的数据不会被恢复。

.Trident智能驭领保障24.10
Trident Protect 24.10不会在数据保护操作期间自动确保KubeVirt VM文件系统的状态一致。如果要使用Trident Protect 24.10保护KubeVirt VM数据、则需要在执行数据保护操作之前手动为文件系统启用冻结/取消冻结功能。这样可确保文件系统处于一致状态。

您可以先配置Trident Protect 24.10、以便在执行数据保护操作期间管理VM文件系统的冻结和解除冻结link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["正在配置虚拟化"^]、然后使用以下命令：

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident®24.10.1及更高版本
从Trident Protect 24.10.1开始、Trident Protect会在数据保护操作期间自动冻结和解除冻结KubeVirt文件系统。或者、您可以使用以下命令禁用此自动行为：

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----


== SnapMirror复制的要求

NetApp SnapMirror复制可用于以下ONTAP解决方案的Trident Protect：

* 内部NetApp FAS、AFF和ASA集群
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* 适用于 NetApp ONTAP 的 Amazon FSX




=== SnapMirror复制的ONTAP集群要求

如果您计划使用SnapMirror复制、请确保ONTAP集群满足以下要求：

* *NetApp Trident*：NetApp Trident 必须存在于使用 ONTAP 作为后端的源 Kubernetes 集群和目标 Kubernetes 集群上。Trident Protect支持使用以下驱动程序支持的存储类通过NetApp SnapMirror技术进行复制：
+
** `ontap-nas` ：NFS
** `ontap-san` ：iSCSI
** `ontap-san` ：足球俱乐部
** `ontap-san` ：NVMe/TCP（要求最低 ONTAP 版本 9.15.1）


* *许可证*：必须在源和目标ONTAP集群上启用使用数据保护包的ONTAP SnapMirror异步许可证。有关详细信息、请参见 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["ONTAP 中的SnapMirror许可概述"^] 。
+
从ONTAP 9.10.1开始、所有许可证均以NetApp许可证文件(NLG)的形式提供、NLG是一个支持多项功能的文件。有关详细信息、请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One附带的许可证"^] 。

+

NOTE: 仅支持 SnapMirror 异步保护。





=== SnapMirror复制的对等注意事项

如果您计划使用存储后端对等、请确保您的环境满足以下要求：

* *集群和SVM*：ONTAP存储后端必须建立对等状态。有关详细信息、请参见 https://docs.netapp.com/us-en/ontap/peering/index.html["集群和 SVM 对等概述"^] 。
+

NOTE: 确保两个ONTAP集群之间的复制关系中使用的SVM名称是唯一的。

* *NetApp Trident 和 SVM*：对等远程 SVM 必须可供目标集群上的 NetApp Trident 使用。
* *托管后端*：您需要在Trident Protect中添加和管理ONTAP存储后端、才能创建复制关系。




=== 用于SnapMirror复制的Trident / ONTAP配置

Trident Protect要求您至少配置一个存储后端、以便为源集群和目标集群同时支持复制。如果源集群和目标集群相同、则目标应用程序应使用与源应用程序不同的存储后端、以获得最佳故障恢复能力。
